version: "2"

volumes:
  settings: # Only required if using PERSISTENT flag (see below)
  pulse:

services:
  browser:
    build: .
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    environment:
      - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
      - "DBUS_SESSION_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
      - "DBUS_STARTER_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
      - "DBUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.sysfs: "1"
      io.balena.features.kernel-modules: "1"
    volumes:
      - "settings:/data" # Only required if using PERSISTENT flag (see below)
      - "pulse:/run/pulse"
  audio:
    image: bh.cr/balenalabs/audio-rpi # where <arch> is one of rpi, armv7hf, aarch64 or amd64
    privileged: true
    labels:
      io.balena.features.dbus: 1 # Only required for bluetooth support
    ports:
      - 4317:4317 # Only required if using PA over TCP socket
    volumes:
      - "pulse:/run/pulse"
